export enum TransfertType {
    SCOLARITE='SCOLARITE',
    SOIN_MEDICAL='SOIN_MEDICAL',
    INVESTISSEMENT='INVESTISSEMENT',
    ECONOMIE_SUR_SALAIRE='ECONOMIE_SUR_SALAIRE',
    CONTRAT_COMMERCIALE='CONTRAT_COMMERCIALE',
    FORMATION_PROFESSIONEL='FORMATION_PROFESSIONEL',
    ACHAT_BIEN='FORMATION_PROFESSIONEL',
    PAIEMENT_SERVICE='PAIEMENT_SERVICE',
    AIDE_FAMILLE='AIDE_FAMILLE',
    TRANSFERT_PERSONELLE='TRANSFERT_PERSONELLE'
}
