export enum TypeDossier {
    SCOLARITE='SCOLARITE',

    SOIN_MEDICAL='SOIN_MEDICAL',

    INVESTISSEMENT='INVESTISSEMENT',

    ECONOMIE_SUR_SALAIRE='ECONOMIE_SUR_SALAIRE',

    CONTRAT_COMMERCIALE='CONTRAT_COMMERCIALE',

    FORMATION_PROFESSIONEL='FORMATION_PROFESSIONEL',

    EMPREINT_EXTERIEUR='EMPREINT_EXTERIEUR'
}
